name: 'Gravatar to Twitter'
author: 'myl7'
description: 'Use Gravatar to provide avatar for Twitter'
inputs:
  consumer_key:
    required: true
  consumer_secret:
    required: true
  key:
    required: true
  secret:
    required: true
  proxy:
    required: false
    default: ''
  email:
    required: false
    default: ''
  image_path:
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://myl7/gravatar2twitter:latest'
