name: CI
on:
  push:
    branches:
      - goshujin-sama
  pull_request:
    branches:
      - goshujin-sama
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build .
